// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/msg.proto

package cmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqHello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHello) Reset()         { *m = ReqHello{} }
func (m *ReqHello) String() string { return proto.CompactTextString(m) }
func (*ReqHello) ProtoMessage()    {}
func (*ReqHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{0}
}

func (m *ReqHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHello.Unmarshal(m, b)
}
func (m *ReqHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHello.Marshal(b, m, deterministic)
}
func (m *ReqHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHello.Merge(m, src)
}
func (m *ReqHello) XXX_Size() int {
	return xxx_messageInfo_ReqHello.Size(m)
}
func (m *ReqHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHello.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHello proto.InternalMessageInfo

func (m *ReqHello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RespHello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespHello) Reset()         { *m = RespHello{} }
func (m *RespHello) String() string { return proto.CompactTextString(m) }
func (*RespHello) ProtoMessage()    {}
func (*RespHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{1}
}

func (m *RespHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespHello.Unmarshal(m, b)
}
func (m *RespHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespHello.Marshal(b, m, deterministic)
}
func (m *RespHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespHello.Merge(m, src)
}
func (m *RespHello) XXX_Size() int {
	return xxx_messageInfo_RespHello.Size(m)
}
func (m *RespHello) XXX_DiscardUnknown() {
	xxx_messageInfo_RespHello.DiscardUnknown(m)
}

var xxx_messageInfo_RespHello proto.InternalMessageInfo

func (m *RespHello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqHello)(nil), "cmsg.ReqHello")
	proto.RegisterType((*RespHello)(nil), "cmsg.RespHello")
}

func init() { proto.RegisterFile("msg/msg.proto", fileDescriptor_d0f0a1b324c95b77) }

var fileDescriptor_d0f0a1b324c95b77 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2d, 0x4e, 0xd7,
	0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0xce, 0x2d, 0x4e, 0x57,
	0x92, 0xe3, 0xe2, 0x08, 0x4a, 0x2d, 0xf4, 0x48, 0xcd, 0xc9, 0xc9, 0x17, 0x12, 0xe2, 0x62, 0xc9,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xe4, 0xb9, 0x38,
	0x83, 0x52, 0x8b, 0x0b, 0x70, 0x2a, 0x48, 0x62, 0x03, 0x9b, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x30, 0x0b, 0xbb, 0x68, 0x5e, 0x00, 0x00, 0x00,
}
