// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/msg/msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqHello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHello) Reset()         { *m = ReqHello{} }
func (m *ReqHello) String() string { return proto.CompactTextString(m) }
func (*ReqHello) ProtoMessage()    {}
func (*ReqHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{0}
}

func (m *ReqHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHello.Unmarshal(m, b)
}
func (m *ReqHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHello.Marshal(b, m, deterministic)
}
func (m *ReqHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHello.Merge(m, src)
}
func (m *ReqHello) XXX_Size() int {
	return xxx_messageInfo_ReqHello.Size(m)
}
func (m *ReqHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHello.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHello proto.InternalMessageInfo

func (m *ReqHello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RespHello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespHello) Reset()         { *m = RespHello{} }
func (m *RespHello) String() string { return proto.CompactTextString(m) }
func (*RespHello) ProtoMessage()    {}
func (*RespHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{1}
}

func (m *RespHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespHello.Unmarshal(m, b)
}
func (m *RespHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespHello.Marshal(b, m, deterministic)
}
func (m *RespHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespHello.Merge(m, src)
}
func (m *RespHello) XXX_Size() int {
	return xxx_messageInfo_RespHello.Size(m)
}
func (m *RespHello) XXX_DiscardUnknown() {
	xxx_messageInfo_RespHello.DiscardUnknown(m)
}

var xxx_messageInfo_RespHello proto.InternalMessageInfo

func (m *RespHello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqSend struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSend) Reset()         { *m = ReqSend{} }
func (m *ReqSend) String() string { return proto.CompactTextString(m) }
func (*ReqSend) ProtoMessage()    {}
func (*ReqSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{2}
}

func (m *ReqSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSend.Unmarshal(m, b)
}
func (m *ReqSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSend.Marshal(b, m, deterministic)
}
func (m *ReqSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSend.Merge(m, src)
}
func (m *ReqSend) XXX_Size() int {
	return xxx_messageInfo_ReqSend.Size(m)
}
func (m *ReqSend) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSend.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSend proto.InternalMessageInfo

func (m *ReqSend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RespSend struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSend) Reset()         { *m = RespSend{} }
func (m *RespSend) String() string { return proto.CompactTextString(m) }
func (*RespSend) ProtoMessage()    {}
func (*RespSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{3}
}

func (m *RespSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSend.Unmarshal(m, b)
}
func (m *RespSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSend.Marshal(b, m, deterministic)
}
func (m *RespSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSend.Merge(m, src)
}
func (m *RespSend) XXX_Size() int {
	return xxx_messageInfo_RespSend.Size(m)
}
func (m *RespSend) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSend.DiscardUnknown(m)
}

var xxx_messageInfo_RespSend proto.InternalMessageInfo

func (m *RespSend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRequest) Reset()         { *m = ReqRequest{} }
func (m *ReqRequest) String() string { return proto.CompactTextString(m) }
func (*ReqRequest) ProtoMessage()    {}
func (*ReqRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{4}
}

func (m *ReqRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRequest.Unmarshal(m, b)
}
func (m *ReqRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRequest.Marshal(b, m, deterministic)
}
func (m *ReqRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRequest.Merge(m, src)
}
func (m *ReqRequest) XXX_Size() int {
	return xxx_messageInfo_ReqRequest.Size(m)
}
func (m *ReqRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRequest proto.InternalMessageInfo

func (m *ReqRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RespRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespRequest) Reset()         { *m = RespRequest{} }
func (m *RespRequest) String() string { return proto.CompactTextString(m) }
func (*RespRequest) ProtoMessage()    {}
func (*RespRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{5}
}

func (m *RespRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespRequest.Unmarshal(m, b)
}
func (m *RespRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespRequest.Marshal(b, m, deterministic)
}
func (m *RespRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespRequest.Merge(m, src)
}
func (m *RespRequest) XXX_Size() int {
	return xxx_messageInfo_RespRequest.Size(m)
}
func (m *RespRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RespRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RespRequest proto.InternalMessageInfo

func (m *RespRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqCall struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCall) Reset()         { *m = ReqCall{} }
func (m *ReqCall) String() string { return proto.CompactTextString(m) }
func (*ReqCall) ProtoMessage()    {}
func (*ReqCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{6}
}

func (m *ReqCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCall.Unmarshal(m, b)
}
func (m *ReqCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCall.Marshal(b, m, deterministic)
}
func (m *ReqCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCall.Merge(m, src)
}
func (m *ReqCall) XXX_Size() int {
	return xxx_messageInfo_ReqCall.Size(m)
}
func (m *ReqCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCall.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCall proto.InternalMessageInfo

func (m *ReqCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RespCall struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCall) Reset()         { *m = RespCall{} }
func (m *RespCall) String() string { return proto.CompactTextString(m) }
func (*RespCall) ProtoMessage()    {}
func (*RespCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6af7a2c9c40ad41, []int{7}
}

func (m *RespCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCall.Unmarshal(m, b)
}
func (m *RespCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCall.Marshal(b, m, deterministic)
}
func (m *RespCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCall.Merge(m, src)
}
func (m *RespCall) XXX_Size() int {
	return xxx_messageInfo_RespCall.Size(m)
}
func (m *RespCall) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCall.DiscardUnknown(m)
}

var xxx_messageInfo_RespCall proto.InternalMessageInfo

func (m *RespCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqHello)(nil), "pb.ReqHello")
	proto.RegisterType((*RespHello)(nil), "pb.RespHello")
	proto.RegisterType((*ReqSend)(nil), "pb.ReqSend")
	proto.RegisterType((*RespSend)(nil), "pb.RespSend")
	proto.RegisterType((*ReqRequest)(nil), "pb.ReqRequest")
	proto.RegisterType((*RespRequest)(nil), "pb.RespRequest")
	proto.RegisterType((*ReqCall)(nil), "pb.ReqCall")
	proto.RegisterType((*RespCall)(nil), "pb.RespCall")
}

func init() { proto.RegisterFile("example/msg/msg.proto", fileDescriptor_e6af7a2c9c40ad41) }

var fileDescriptor_e6af7a2c9c40ad41 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0xcf, 0x2d, 0x4e, 0x07, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21,
	0xa6, 0x82, 0x24, 0x25, 0x39, 0x2e, 0x8e, 0xa0, 0xd4, 0x42, 0x8f, 0xd4, 0x9c, 0x9c, 0x7c, 0x21,
	0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b,
	0x49, 0x9e, 0x8b, 0x33, 0x28, 0xb5, 0xb8, 0x00, 0xb7, 0x02, 0x59, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2,
	0xe0, 0xd4, 0xbc, 0x14, 0xac, 0xd2, 0x60, 0xf3, 0x8b, 0x0b, 0x70, 0xca, 0x2b, 0x70, 0x71, 0x05,
	0xa5, 0x16, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x60, 0x55, 0xa1, 0xc8, 0xc5, 0x0d, 0x32,
	0x01, 0x9f, 0x12, 0x88, 0x1b, 0x9c, 0x13, 0x73, 0x72, 0xf0, 0xb9, 0x01, 0x97, 0x7c, 0x12, 0x1b,
	0x38, 0x38, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x28, 0x45, 0x35, 0x27, 0x01, 0x00,
	0x00,
}
